# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N4zPKmKfswoUvsyoZX8UAMCTjKi6x-tM
"""

import math
class Yadro:
  def __init__(self, A, Z):
    self.A = A
    self.Z = Z
  def energy(self):
    if self.A % 2 == 1:
      a5 = 0
    elif (self.A/2) % 2 == 0:
      a5 = 34
    elif (self.A/2) % 2 == 1:
      a5 = -34
    return ((15,7*self.A-17,8*self.A**(2/3)-0,71*(self.Z**2/self.A**(1/3))-23,7*((self.A-2*Z)**2)/self.A+a5*self.A**(-3/4))/self.A)
  def mass(self):
    mp = 7,289
    mn = 8.071
    retutn ((self.A - self.Z)*mn + self.Z*mp - self.ehergy())
  def radius(self):
    r0 = 1,3
    return r0*A**(1/3)
  def beta(self):
    z0 = self.A/(2 + 0.015*A**(2/3))
    if z0 > Z:
      print("Предрасположен к бета-минус распаду")
    elif z0 < Z:
      print("Предрасположен к бета-плюс распаду")
    else:
      print("Не предрасположен к бета распаду")
  def fission(self):
    if self.A % 2 == 4:
      print("Распдается на два четно-четных осколка")
    else:
      print("Деление на два четно-четных осколка невозможно")